; JIMMY LAM
; DR. NGUYEN
; CIS11
; CHARACTER COUNTER

.ORIG x3000

; INITIALIZE THE STACK
LD R6, STACK_ADDR

; MAIN SUBROUTINE

; MAIN

; GET A STRING FROM THE USER
GET_USER_STRING
; BACKUP ALL USED REGISTERS, STORE ON THE STACK
; MANAGE STACK OVERFLOW AND RESERVE ENOUGH SPACE ON THE STACK
ADD R6, R6, #-1
STR R7, R6, #0
ADD R6, R6, #-1
STR R6, R6, #0
ADD R6, R6, #-1
STR R5, R6, #0
ADD R6, R6, #-1
STR R4, R6, #0
ADD R6, R6, #-1
STR R3, R6, #0
ADD R6, R6, #-1
STR R2, R6, #0
ADD R6, R6, #-1
STR R1, R6, #0

; PROMPT USER MESSAGE
LEA R0, PROMPT_3200
PUTS

AND R5, R5, #0
LD R2, NEWLINE

NOT R2, R2
ADD R2, R2, #1

; LOAD ADDRESS OF -97 INTO R3
LEA R3, COMPLEMENT97
LDR R3, R3, #0

; TAKE AND STORE USER'S INPUTS
USER_INPUT
GETC
OUT
ADD R6, R0, #-16
ADD R6, R6, #-16
BRz USER_INPUT

ADD R6, R0, #-10
BRz USER_OUTPUT

LEA R5, STACK
ADD R0, R0, R3
BRz COUNTER

; TAKING INPUT AND TRAVERSE ONE BY ONE
COMPARISON
ADD R5, R5, #1
ADD R0, R0, #-1
BRp COMPARISON

; CHECK FOR HOW MANY ALPHABETS ARE REPEATED IN THE STRING
COUNTER
LDR R0, R5, #0
ADD R0, R0, #1
STR R0, R5, #0
BR USER_INPUT

; OUTPUT THE CONTENTS OF THE STACK
USER_OUTPUT
LD R2, DEC26
LD R4, DEC97
ADD R0, R4, #0

LEA R5, STACK
LD R3, DEC48

; PRINTS IN A FORMAT OF ALPHABET: # OF TIMES
PRINT_FORMAT
OUT

ADD R0, R0, #0
LD R0, COLON
OUT

LDR R0, R5, #0
ADD R5, R5, #1
ADD R0, R0, R3
OUT

LD R0, NEWLINE
OUT

ADD R4, R4, #1
ADD R0, R4, #0
ADD R2, R2, #-1
BRp PRINT_FORMAT

; RESTORE THE REGISTERS FROM R0 TO R7
LDR R0, R6, #0
ADD R6, R6, #1
LDR R1, R6, #0
ADD R6, R6, #1
LDR R2, R6, #0
ADD R6, R6, #1
LDR R3, R6, #0
ADD R6, R6, #1
LDR R4, R6, #0
ADD R6, R6, #1
LDR R5, R6, #0
ADD R6, R6, #1
LDR R6, R6, #0
ADD R6, R6, #1
LDR R7, R6, #0
ADD R6, R6, #1

; RETURN FROM THE SUBROUTINE
RET

HALT
; RESTORE ALL USED REGISTERS, USING PROPER STACK DISCIPLINE

; SUBROUTINE DATA

PROMPT_3200 .STRINGZ "Enter something (in lowercase), Press [enter] to finish: \n"
STACK .BLKW #50
NEWLINE .FILL x0A
DEC26 .FILL #26
DEC48 .FILL #48
DEC97 .FILL #97
COLON .FILL x003A
COMPLEMENT97 .FILL #-97

; STACK ADDRESS
STACK_ADDR .FILL xFE00
; ADDRESSES OF SUBROUTINES, OTHER THAN MAIN
GET_USER_STRING_ADDR .FILL x3200
ADDR .FILL x4000

; RESERVE MEMORY FOR STRINGS IN THE PROGRAM
USER_PROMPT .STRINGZ "Enter a string: "
USER_STRING .BLKW x100
.END